[2020-12-21T22:12:27.755Z] ERROR something went wrong: TokenExpiredError: jwt expired (host=nox-desktop, name=network_logger, pid=2296)
[2020-12-21T22:12:42.179Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=6936)
[2020-12-21T22:14:38.787Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=15144)
[2020-12-21T22:14:43.805Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=15144)
[2020-12-21T22:14:48.818Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=15144)
[2020-12-21T22:14:59.918Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=15144)
[2020-12-21T22:15:04.946Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=15144)
[2020-12-21T22:15:06.426Z] ERROR something went wrong: GraphQLError: Field "addComment" argument "postID" of type "String!" is required, but it was not provided.
    at Object.leave (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ProvidedRequiredArgumentsRule.js:62:33)
    at Object.leave (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:344:29)
    at Object.leave (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:390:21)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=15144)
[2020-12-21T22:15:18.026Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=15144)
[2020-12-21T22:15:29.088Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=15144)
[2020-12-21T22:15:34.114Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=15144)
[2020-12-21T22:19:58.695Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=4196)
[2020-12-21T22:20:16.257Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Post.user.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:471:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=4196)
[2020-12-21T22:20:53.951Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=18776)
[2020-12-21T22:47:16.705Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:17.347Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:22.366Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:23.401Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:24.430Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:25.460Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:26.495Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:28.536Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:31.558Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:36.582Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:44.622Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:47:57.655Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:48:18.678Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:48:52.703Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:49:48.345Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:50:24.271Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:51:15.947Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:51:21.744Z] ERROR something went wrong: GraphQLError: Field "likes" of type "[Like!]!" must have a selection of subfields. Did you mean "likes { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:52:45.345Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:52:50.360Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T22:52:51.964Z] ERROR something went wrong: GraphQLError: Field "likes" of type "[Like!]!" must have a selection of subfields. Did you mean "likes { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=10496)
[2020-12-21T23:16:14.860Z] ERROR something went wrong: QueryFailedError: null value in column "text" of relation "like" violates not-null constraint
    at new QueryFailedError (H:\projects\network\network_backend\src\error\QueryFailedError.ts:9:9)
    at Query.<anonymous> (H:\projects\network\network_backend\src\driver\postgres\PostgresQueryRunner.ts:220:30)
    at Query.handleError (H:\projects\network\network_backend\node_modules\pg\lib\query.js:128:19)
    at Client._handleErrorMessage (H:\projects\network\network_backend\node_modules\pg\lib\client.js:335:17)
    at Connection.emit (events.js:315:20)
    at H:\projects\network\network_backend\node_modules\pg\lib\connection.js:115:12
    at Parser.parse (H:\projects\network\network_backend\node_modules\pg-protocol\src\parser.ts:102:9)
    at Socket.<anonymous> (H:\projects\network\network_backend\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12) (host=nox-desktop, name=network_logger, pid=21728)
[2020-12-21T23:17:48.471Z] ERROR something went wrong: QueryFailedError: null value in column "text" of relation "like" violates not-null constraint
    at new QueryFailedError (H:\projects\network\network_backend\src\error\QueryFailedError.ts:9:9)
    at Query.<anonymous> (H:\projects\network\network_backend\src\driver\postgres\PostgresQueryRunner.ts:220:30)
    at Query.handleError (H:\projects\network\network_backend\node_modules\pg\lib\query.js:128:19)
    at Client._handleErrorMessage (H:\projects\network\network_backend\node_modules\pg\lib\client.js:335:17)
    at Connection.emit (events.js:315:20)
    at H:\projects\network\network_backend\node_modules\pg\lib\connection.js:115:12
    at Parser.parse (H:\projects\network\network_backend\node_modules\pg-protocol\src\parser.ts:102:9)
    at Socket.<anonymous> (H:\projects\network\network_backend\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12) (host=nox-desktop, name=network_logger, pid=21728)
[2020-12-21T23:18:31.419Z] ERROR something went wrong: QueryFailedError: null value in column "text" of relation "like" violates not-null constraint
    at new QueryFailedError (H:\projects\network\network_backend\src\error\QueryFailedError.ts:9:9)
    at Query.<anonymous> (H:\projects\network\network_backend\src\driver\postgres\PostgresQueryRunner.ts:220:30)
    at Query.handleError (H:\projects\network\network_backend\node_modules\pg\lib\query.js:128:19)
    at Client._handleErrorMessage (H:\projects\network\network_backend\node_modules\pg\lib\client.js:335:17)
    at Connection.emit (events.js:315:20)
    at H:\projects\network\network_backend\node_modules\pg\lib\connection.js:115:12
    at Parser.parse (H:\projects\network\network_backend\node_modules\pg-protocol\src\parser.ts:102:9)
    at Socket.<anonymous> (H:\projects\network\network_backend\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12) (host=nox-desktop, name=network_logger, pid=15756)
[2020-12-21T23:20:43.900Z] ERROR something went wrong: QueryFailedError: null value in column "text" of relation "like" violates not-null constraint
    at new QueryFailedError (H:\projects\network\network_backend\src\error\QueryFailedError.ts:9:9)
    at Query.<anonymous> (H:\projects\network\network_backend\src\driver\postgres\PostgresQueryRunner.ts:220:30)
    at Query.handleError (H:\projects\network\network_backend\node_modules\pg\lib\query.js:128:19)
    at Client._handleErrorMessage (H:\projects\network\network_backend\node_modules\pg\lib\client.js:335:17)
    at Connection.emit (events.js:315:20)
    at H:\projects\network\network_backend\node_modules\pg\lib\connection.js:115:12
    at Parser.parse (H:\projects\network\network_backend\node_modules\pg-protocol\src\parser.ts:102:9)
    at Socket.<anonymous> (H:\projects\network\network_backend\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12) (host=nox-desktop, name=network_logger, pid=10376)
[2020-12-21T23:21:11.772Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=10376)
[2020-12-21T23:21:17.005Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=9264)
[2020-12-21T23:21:17.011Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=9264)
[2020-12-21T23:21:18.475Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=9264)
[2020-12-21T23:21:26.099Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=9264)
[2020-12-21T23:21:26.722Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=9264)
[2020-12-21T23:21:32.098Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=9264)
[2020-12-21T23:21:59.262Z] ERROR something went wrong: TokenExpiredError: jwt expired
    at H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:152:21
    at getSecret (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (H:\projects\network\network_backend\node_modules\jsonwebtoken\verify.js:94:10)
    at authenticateToken (H:\projects\network\network_backend\src\utils\middlewares\auth.ts:12:9)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\projects\network\network_backend\node_modules\express\lib\router\route.js:112:3)
    at newFn (H:\projects\network\network_backend\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (H:\projects\network\network_backend\node_modules\express\lib\router\layer.js:95:5) (host=nox-desktop, name=network_logger, pid=8724)
[2020-12-21T23:22:31.981Z] ERROR something went wrong: QueryFailedError: null value in column "text" of relation "like" violates not-null constraint
    at new QueryFailedError (H:\projects\network\network_backend\src\error\QueryFailedError.ts:9:9)
    at Query.<anonymous> (H:\projects\network\network_backend\src\driver\postgres\PostgresQueryRunner.ts:220:30)
    at Query.handleError (H:\projects\network\network_backend\node_modules\pg\lib\query.js:128:19)
    at Client._handleErrorMessage (H:\projects\network\network_backend\node_modules\pg\lib\client.js:335:17)
    at Connection.emit (events.js:315:20)
    at H:\projects\network\network_backend\node_modules\pg\lib\connection.js:115:12
    at Parser.parse (H:\projects\network\network_backend\node_modules\pg-protocol\src\parser.ts:102:9)
    at Socket.<anonymous> (H:\projects\network\network_backend\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12) (host=nox-desktop, name=network_logger, pid=8724)
[2020-12-21T23:28:01.708Z] ERROR something went wrong: GraphQLError: Field "getLikeCountFromPost" of type "LikeCountResponse!" must have a selection of subfields. Did you mean "getLikeCountFromPost { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=12664)
[2020-12-21T23:29:45.881Z] ERROR something went wrong: GraphQLError: Cannot query field "totalCount" on type "LikeCountResponse". Did you mean "likeCount"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\FieldsOnCorrectTypeRule.js:46:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=11892)
[2020-12-21T23:41:53.140Z] ERROR something went wrong: Error: you already liked this post
    at PostResolver.likePost (H:\projects\network\network_backend\src\resolvers\post.resolver.ts:68:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:83:26
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=22068)
[2020-12-21T23:41:56.872Z] ERROR something went wrong: Error: you already liked this post
    at PostResolver.likePost (H:\projects\network\network_backend\src\resolvers\post.resolver.ts:68:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:83:26
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=22068)
[2020-12-21T23:42:04.577Z] ERROR something went wrong: Error: you already liked this post
    at PostResolver.likePost (H:\projects\network\network_backend\src\resolvers\post.resolver.ts:68:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:83:26
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=22068)
[2020-12-21T23:42:04.747Z] ERROR something went wrong: Error: you already liked this post
    at PostResolver.likePost (H:\projects\network\network_backend\src\resolvers\post.resolver.ts:68:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:83:26
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=22068)
[2020-12-21T23:42:04.917Z] ERROR something went wrong: Error: you already liked this post
    at PostResolver.likePost (H:\projects\network\network_backend\src\resolvers\post.resolver.ts:68:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:83:26
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=22068)
[2020-12-21T23:42:34.402Z] ERROR something went wrong: Error: you already liked this post
    at PostResolver.likePost (H:\projects\network\network_backend\src\resolvers\post.resolver.ts:68:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:83:26
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=22068)
[2020-12-21T23:47:30.512Z] ERROR something went wrong: GraphQLError: Field "getPosts" of type "[Post!]" must have a selection of subfields. Did you mean "getPosts { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=21628)
[2020-12-21T23:53:26.779Z] ERROR something went wrong: GraphQLError: Field "user" of type "User!" must have a selection of subfields. Did you mean "user { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=11344)
[2020-12-21T23:53:31.922Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Comment.likes.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:626:25
    at from (<anonymous>)
    at completeListValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:613:49) (host=nox-desktop, name=network_logger, pid=11344)
[2020-12-21T23:54:36.506Z] ERROR something went wrong: GraphQLError: Field "likes" of type "[Like!]!" must have a selection of subfields. Did you mean "likes { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=11344)
[2020-12-21T23:55:06.871Z] ERROR something went wrong: GraphQLError: Field "likes" of type "[Like!]!" must have a selection of subfields. Did you mean "likes { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=11344)
[2020-12-21T23:55:18.558Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Comment.likes.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:626:25
    at from (<anonymous>)
    at completeListValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:613:49) (host=nox-desktop, name=network_logger, pid=11344)
[2020-12-21T23:55:28.146Z] ERROR something went wrong: GraphQLError: Field "text" must not have a selection since type "String!" has no subfields.
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:33:33)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=11344)
[2020-12-21T23:55:55.494Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Post.likes.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:626:25
    at from (<anonymous>)
    at completeListValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:613:49) (host=nox-desktop, name=network_logger, pid=11344)
[2020-12-21T23:58:10.439Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Post.likes.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:626:25
    at from (<anonymous>)
    at completeListValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:613:49) (host=nox-desktop, name=network_logger, pid=4700)
[2020-12-21T23:58:46.867Z] ERROR something went wrong: Error: you already liked this post
    at PostResolver.likePost (H:\projects\network\network_backend\src\resolvers\post.resolver.ts:69:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:83:26
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=13704)
[2020-12-22T00:01:29.326Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Comment.likes.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:626:25
    at from (<anonymous>)
    at completeListValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:613:49) (host=nox-desktop, name=network_logger, pid=6680)
[2020-12-22T00:02:59.882Z] ERROR something went wrong: Error: Cannot return null for non-nullable field Like.user.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:626:25
    at from (<anonymous>)
    at completeListValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:613:49) (host=nox-desktop, name=network_logger, pid=17312)
[2020-12-22T00:04:24.837Z] ERROR something went wrong: GraphQLError: Field "user" of type "User!" must have a selection of subfields. Did you mean "user { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=17864)
[2020-12-22T00:04:38.117Z] ERROR something went wrong: GraphQLError: Field "user" of type "User!" must have a selection of subfields. Did you mean "user { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=17232)
[2020-12-22T00:04:39.188Z] ERROR something went wrong: GraphQLError: Field "user" of type "User!" must have a selection of subfields. Did you mean "user { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=17232)
[2020-12-22T22:14:44.746Z] ERROR something went wrong: Error: you already liked this post
    at CommentResolver.likeComment (H:\projects\network\network_backend\src\resolvers\comment.resolver.ts:63:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:83:26
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=29820)
[2020-12-22T22:16:33.407Z] ERROR something went wrong: GraphQLError: Field "followers" of type "[User!]!" must have a selection of subfields. Did you mean "followers { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=32392)
[2020-12-22T22:16:43.934Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32392)
[2020-12-22T22:20:52.177Z] ERROR something went wrong: Error: Relations "post.comments", "post.user", "post.likes", "post.likes.user", "post.comments.user", "post.comments.likes", "post.comments.likes.user" were not found; please check if relations are correct and they exist in your entities.
    at new FindRelationsNotFoundError (H:\projects\network\network_backend\src\error\FindRelationsNotFoundError.ts:7:9)
    at Function.FindOptionsUtils.applyOptionsToQueryBuilder (H:\projects\network\network_backend\src\find-options\FindOptionsUtils.ts:147:23)
    at EntityManager.<anonymous> (H:\projects\network\network_backend\src\entity-manager\EntityManager.ts:788:26)
    at step (H:\projects\network\network_backend\node_modules\typeorm\node_modules\tslib\tslib.js:141:27)
    at Object.next (H:\projects\network\network_backend\node_modules\typeorm\node_modules\tslib\tslib.js:122:57)
    at H:\projects\network\network_backend\node_modules\typeorm\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (H:\projects\network\network_backend\node_modules\typeorm\node_modules\tslib\tslib.js:111:16)
    at EntityManager.findOne (H:\projects\network\network_backend\node_modules\typeorm\entity-manager\EntityManager.js:508:24)
    at Repository.findOne (H:\projects\network\network_backend\src\repository\Repository.ts:370:29) (host=nox-desktop, name=network_logger, pid=31052)
[2020-12-22T22:21:34.564Z] ERROR something went wrong: Error: Relations "post.comments", "post.user", "post.likes", "post.likes.user", "post.comments.user", "post.comments.likes", "post.comments.likes.user" were not found; please check if relations are correct and they exist in your entities.
    at new FindRelationsNotFoundError (H:\projects\network\network_backend\src\error\FindRelationsNotFoundError.ts:7:9)
    at Function.FindOptionsUtils.applyOptionsToQueryBuilder (H:\projects\network\network_backend\src\find-options\FindOptionsUtils.ts:147:23)
    at EntityManager.<anonymous> (H:\projects\network\network_backend\src\entity-manager\EntityManager.ts:788:26)
    at step (H:\projects\network\network_backend\node_modules\typeorm\node_modules\tslib\tslib.js:141:27)
    at Object.next (H:\projects\network\network_backend\node_modules\typeorm\node_modules\tslib\tslib.js:122:57)
    at H:\projects\network\network_backend\node_modules\typeorm\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (H:\projects\network\network_backend\node_modules\typeorm\node_modules\tslib\tslib.js:111:16)
    at EntityManager.findOne (H:\projects\network\network_backend\node_modules\typeorm\entity-manager\EntityManager.js:508:24)
    at Repository.findOne (H:\projects\network\network_backend\src\repository\Repository.ts:370:29) (host=nox-desktop, name=network_logger, pid=31052)
[2020-12-22T22:22:30.699Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=28756)
[2020-12-22T22:22:58.127Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=5408)
[2020-12-22T22:23:10.200Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=5408)
[2020-12-22T22:23:53.551Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32712)
[2020-12-22T22:23:54.856Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32712)
[2020-12-22T22:23:59.865Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32712)
[2020-12-22T22:24:08.753Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=26612)
[2020-12-22T22:24:11.627Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=26612)
[2020-12-22T22:24:19.369Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32160)
[2020-12-22T22:24:20.233Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32160)
[2020-12-22T22:27:11.360Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=24604)
[2020-12-22T22:27:22.459Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32272)
[2020-12-22T22:27:23.840Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32272)
[2020-12-22T22:27:47.357Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32244)
[2020-12-22T22:27:48.398Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=32244)
[2020-12-22T22:27:54.909Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=20120)
[2020-12-22T22:27:56.743Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=20120)
[2020-12-22T22:28:05.308Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=27352)
[2020-12-22T22:28:06.148Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=27352)
[2020-12-22T22:31:27.215Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=31440)
[2020-12-22T22:31:39.349Z] ERROR something went wrong: Error: Cannot return null for non-nullable field User.followers.
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:561:13)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10)
    at completeObjectValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:739:10)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:592:12)
    at completeValue (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:558:21)
    at resolveField (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:474:19)
    at executeFields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:294:18)
    at collectAndExecuteSubfields (H:\projects\network\network_backend\node_modules\graphql\execution\execute.js:749:10) (host=nox-desktop, name=network_logger, pid=29052)
[2020-12-22T22:33:41.970Z] ERROR something went wrong: GraphQLError: Field "likes" of type "[Like!]!" must have a selection of subfields. Did you mean "likes { ... }"?
    at Object.Field (H:\projects\network\network_backend\node_modules\graphql\validation\rules\ScalarLeafsRule.js:40:31)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:323:29)
    at Object.enter (H:\projects\network\network_backend\node_modules\graphql\utilities\TypeInfo.js:370:25)
    at visit (H:\projects\network\network_backend\node_modules\graphql\language\visitor.js:243:26)
    at validate (H:\projects\network\network_backend\node_modules\graphql\validation\validate.js:69:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:98:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) (host=nox-desktop, name=network_logger, pid=29768)
[2020-12-22T22:36:05.802Z] ERROR something went wrong: Error: you already liked this post
    at CommentResolver.likeComment (H:\projects\network\network_backend\src\resolvers\comment.resolver.ts:63:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:83:26
    at dispatchHandler (H:\projects\network\network_backend\node_modules\type-graphql\dist\resolvers\helpers.js:82:24)
    at graphqlMiddleware (H:\projects\network\network_backend\node_modules\express-graphql\index.js:125:26) (host=nox-desktop, name=network_logger, pid=29768)
